##### Simulation code for subgroup transportability
# codes for obtaining the balancing intercepts are borrowed from https://github.com/pzivich/publications-code/blob/master/ReBalancingIntercept/balance_intercept.R 

###########------- Libraries
library("mvtnorm")
library("tidyverse")
library("rootSolve")
library("Hmisc")
library("SciViews")
library("gam")
library("nnet")
library("boot")
library("dummy")
library("latex2exp")

###########------- Parameters specification
nsim=5000
nGetTrue=1000000
p=10
beta_coefs=matrix(rep(ln(1.05),p),byrow=F,nrow=1)      # coef of R model
# beta_coefs=matrix(c(rep(ln(1.1),p/2),rep(ln(1.2),p/2)),byrow=F,nrow=1)     # coef of R model for external
xi_coefs=matrix(c(rep(ln(1.1),p/2),rep(ln(1.5),p/2)),byrow=F,nrow=1)      # coef of S model
zeta_coefs=matrix(c(rep(ln(1.1),p/2),rep(ln(1.5),p/2)),byrow=F,nrow=1)    # coef of S model
alpha_1=matrix(c(rep(1,p/2+1),rep(-1,p/2)),byrow=F,nrow=1)     # coef of A model
alpha_2=matrix(c(rep(1.5,p/2+1),rep(-1.5,p/2)),byrow=F,nrow=1)                                    # coef of A model
alpha_3=matrix(c(rep(2,p/2+1),rep(-2,p/2)),byrow=F,nrow=1)       # coef of A model
theta_0=c(1,2,rep(0.75,p-1))                        # coef of Y0 model

###########------- Data generation (for the use of both internal and external case)
Gen=function(n,n_m){
  ### Function to be solved - this function will be called to solve for intercepts in each data generation model
  tosolve <- function(ints, fxname, goalmarg){
    values <- fxname(ints)                          # simulated individual expected values at given intercept value
    if(is.null(dim(values))){                       # obtain mean of simulated individual expected values
      empmeans <-  mean(values)}else{
        empmeans <-  colMeans(values)
      }     
    diff = empmeans - goalmarg                      # difference from empirical mean to goal marginal distribution
    return(diff)                              
  }
  
  ## X
  X1_latent=rnorm(n,0,1)
  X1_sort=split(sort(X1_latent), sort(rep_len(1:9, length(X1_latent))))
  X1=as.factor(ifelse(X1_latent%in%X1_sort$`1` ,1,ifelse(X1_latent%in%c(X1_sort$`2`,X1_sort$`3`),2, ifelse(X1_latent%in%c(X1_sort$`4`,X1_sort$`5`,X1_sort$`6`),3, ifelse(X1_latent%in%c(X1_sort$`7`,X1_sort$`8`),4, 5)))))
  X1_1=ifelse(X1==1,1,0);X1_2=ifelse(X1==2,1,0);X1_3=ifelse(X1==3,1,0);X1_4=ifelse(X1==4,1,0);X1_5=ifelse(X1==5,1,0)
  sigma=matrix(rep(0.25,(p-1)*(p-1)),nrow=(p-1))
  diag(sigma)=0.5
  X2_10=rmvnorm(n, rep(0.1,p-1), sigma)
  X=matrix(cbind(X1, X2_10),byrow=F,ncol=p)
  
  ## R
  gen_pr_r <- function(beta0){
    prob_r <- plogis(as.numeric(beta0 + beta_coefs%*%t(X)) )  # probability generated by model at given intercept value
    return(prob_r)
  }
  goalmarg_r <- n_m/n
  rootr <- multiroot(f=tosolve, start=c(-1), fxname=gen_pr_r, goalmarg=goalmarg_r, atol=1e-12)$root # find root for R model
  R=rbinom(n, size=1, p=gen_pr_r(rootr))                     # simulate R using intercept solution
  
  ## S
  gen_pr_s <- function(xi_zeta0){
    odds <- matrix(nrow=length(R[R==1]), ncol=2)             # create empty matrix to store odds
    odds[,1] <- exp(xi_zeta0[1] + xi_coefs%*%t(X[R==1,]))    # odds(1vs0) at given intercept value
    odds[,2] <- exp(xi_zeta0[2] + zeta_coefs%*%t(X[R==1,]))  # odds(2vs0) at given intercept value
    denom <- as.matrix(1 + rowSums(odds))                    # sum of 3 odds to be used as denominator of pr
    prob_s <- cbind(1/denom, odds[,1]/denom)                 
    return(prob_s)
  }
  goalmarg_s <- c(4/(4+2+1), 2/(4+2+1))
  roots <- multiroot(f=tosolve, start=c(-3,-2), fxname=gen_pr_s, goalmarg=goalmarg_s, atol=1e-12)$root # find root for mediator model
  prS <- cbind(gen_pr_s(roots), 1 - rowSums(gen_pr_s(roots))) # obtain probabilities for each S level using intercept solutions
  S_R <- Hmisc::rMultinom(prS,1)
  S=rep(NA,length(R))
  S[R==1]=S_R
  
  ## A
  A1=rbinom(length(S_R[S_R==1]), size=1, p=plogis(as.numeric(alpha_1%*%t(data.frame(cbind(rep(1,length(S_R[S_R==1])),X[which(S_R==1),]))))))
  A2=rbinom(length(S_R[S_R==2]), size=1, p=plogis(as.numeric(alpha_2%*%t(data.frame(cbind(rep(1,length(S_R[S_R==2])),X[which(S_R==2),]))))))
  A3=rbinom(length(S_R[S_R==3]), size=1, p=plogis(as.numeric(alpha_3%*%t(data.frame(cbind(rep(1,length(S_R[S_R==3])),X[which(S_R==3),]))))))
  A_R=rep(NA,length(S_R));A_R[S_R==1]=A1;A_R[S_R==2]=A2;A_R[S_R==3]=A3
  A=rep(NA,length(R));A[R==1]=A_R
  
  ## Y
  f1=function(x) sin(x)/5
  f2=function(x) exp(-0.25*x)
  f3=function(x) 0.02*x^2+(2*(1+0.1*x))^2+2*(0.015*x)^3
  Y1=1+5+f1(theta_0[3]*X[,2])+f1(theta_0[4]*X[,3])+f1(theta_0[5]*X[,4])+f2(theta_0[6]*X[,5])+f2(theta_0[7]*X[,6])+f2(theta_0[8]*X[,7])+f3(theta_0[9]*X[,8])+f3(theta_0[10]*X[,9])+f3(theta_0[11]*X[,10])+
    0.2*X1_1+0.4*X1_2-0.5*X1_3+0.1*X1_4-0.01*X1_5+0.2*X[,2]+0.2*X[,3]-0.2*X[,4]-0.2*X[,5]+
    rnorm(n,0,10)
  Y0=1+f1(theta_0[3]*X[,2])+f1(theta_0[4]*X[,3])+f1(theta_0[5]*X[,4])+f2(theta_0[6]*X[,5])+f2(theta_0[7]*X[,6])+f2(theta_0[8]*X[,7])+f3(theta_0[9]*X[,8])+f3(theta_0[10]*X[,9])+f3(theta_0[11]*X[,10])+
    rnorm(n,0,10)  
  Y=Y0*(1-A)+Y1*A
  Y_R=Y[R==1]
  
  return(data.frame(X,R,S,A,Y,Y1,Y0))
}


# ###########------ True value of psi_{1,1}(x_tilde):E(Y1|X1=x_tilde,S=1), and phi_{1}(x_tilde):E(Y1|X1=x_tilde,R=0)
GetTrue=function(n, n_m, x_tilde){
  mean_psi=NULL
  mean_phi=NULL
  for (i in 1:nGetTrue) {
    Data=Gen(n, n_m)
    Y_1=Data$Y1
    Y_0=Data$Y0
    mean_psi_temp=mean(Y_1[which(Data$X1==x_tilde & Data$S==1)])
    mean_psi=c(mean_psi,mean_psi_temp)
    mean_phi_temp=mean(Y_1[which(Data$X1==x_tilde & Data$R==0)])
    mean_phi=c(mean_phi,mean_phi_temp)
  }
  psi=mean(mean_psi);phi=mean(mean_phi)
  results=c(psi,phi)
  return(results)
}
